### ISSUE TITLE
Prisma - support hasIntersection operation

### ISSUE THREAD

**Issue by fabianlocker** [cerbos/query-plan-adapters#52]
# Is there an existing issue for this?

- [x] I have searched the existing issues

# Feature description

With Cerbos policies it is possible to check for intersections of list elements, and make decisions based on `hasIntersection`.
It would be a great addition to relational queries and scalar lists to support this operation also for the Query Plan Adapter for Prisma ORM.

E.g. Entities with scalar lists or one-to-many / many-to-many relations could be checked for common attributes between principal and resource definition.

# What would the ideal solution look like to you?

It would be ideal if the hasIntersection operation could be handled like other supported operations. 

Who it could look like as an inspiration:

Relational:
```
model Resource {
  id               String         @id @default(cuid())
  aString          String
  aNumber          Int
  aBool            Boolean
  ownedBy          User[]
  createdBy        User           @relation(fields: [creatorId], references: [id], name: "creator")
  creatorId        String
  nested           NestedResource @relation(fields: [nestedResourceId], references: [id])
  nestedResourceId String
  tags             Tag[].         // new tags relation field
}


model Tag {
  id        String @id @default(cuid())
  value     String
  resources Resource[] // new resources relation field
}
```

Scalar List: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-scalar-lists-arrays
```
model Resource {
  id               String         @id @default(cuid())
  aString          String
  aNumber          Int
  aBool            Boolean
  ownedBy          User[]
  createdBy        User           @relation(fields: [creatorId], references: [id], name: "creator")
  creatorId        String
  nested           NestedResource @relation(fields: [nestedResourceId], references: [id])
  nestedResourceId String
  tags             String[].         // new tags scalar list field
}
```

Cerbos Policy
```
# yaml-language-server: $schema=https://api.cerbos.dev/latest/cerbos/policy/v1/Policy.schema.json

apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: default
  resource: resource
  rules:
    - actions:
        - "hasIntersection"
      effect: EFFECT_ALLOW
      roles:
        - USER
      condition:
        match: 
          expr: hasIntersection(request.resource.attr.tags, request.principal.attr.tags)
```

Principal:
```
principal: { id: "user1", roles: ["USER"], attributes: {tags: ["Tag-1", "Tag-2"]} },
```

The resulting Prisma filter objects should look like:

Relational:
```
prisma.resource.findMany({
  where: { tags: { some: {name: in: ["Tag-1", "Tag-2"] } } },
})
```

Scalar List:
```
prisma.resource.findMany({
  where: { tags: { has: ["Tag-1", "Tag-2"] } },
})
```
